options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/fabled-mystery-316508/${_SERVICE_NAME}", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/fabled-mystery-316508/${_SERVICE_NAME}"]

  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
        [
          "-i",
          "gcr.io/fabled-mystery-316508/${_SERVICE_NAME}",
          "-s",
          "fabled-mystery-316508:${_REGION}:${_INSTANCE_NAME}",
          "-e",
          "DATABASE_HOST=/cloudsql/fabled-mystery-316508:europe-west2:djangodb-1",
          "-e",
          "DATABASE_PORT=5432",
          "-e",
          "DATABASE_USER=admin",
          "-e",
          "DATABASE_PASSWORD=Admin123",
          "-e",
          "DATABASE_NAME=testmaindb",
          "--",
          "python",
          "manage.py",
          "migrate",
        ]

substitutions:
  _INSTANCE_NAME: hello-world-1
  _REGION: europe-west2
  _SERVICE_NAME: hello-world-1
  _SECRET_SETTINGS_NAME: django_settings

images:
  - "gcr.io/fabled-mystery-316508/${_SERVICE_NAME}"
